- name: Ensure ~/.vim folder is present.
  file:
    path: "~/.vim"
    state: directory

- name: Symlink language specific formatting files.
  file:
    src: "{{ dotfiles_repo_local_destination }}/ftplugin"
    dest: "~/.vim/ftplugin"
    state: link

- name: Symlink theme files.
  file:
    src: "{{ dotfiles_repo_local_destination }}/colors"
    dest: "~/.vim/colors"
    state: link

- name: Clone Vundle.
  git:
    repo: 'https://github.com/VundleVim/Vundle.vim.git'
    dest: '~/.vim/bundle/Vundle.vim'

- name: Install Vundle plugins.
  command: vim +PluginInstall +qall
