- name: Install zsh in Ubuntu.
  when: platform == "ubuntu"
  become: yes
  apt:
    name: zsh
    state: present

# TODO add install for homebrew

- name: Download oh-my-zsh.
  git:
    repo: 'https://github.com/ohmyzsh/ohmyzsh.git'
    dest: '~/.oh-my-zsh'

- name: Change default shell to zsh.
  become: yes
  command: chsh -s /usr/bin/zsh {{ ansible_user_id }}

- name: Install zsh-autosuggestions plugin.
  git:
    repo: "https://github.com/zsh-users/zsh-autosuggestions"
    dest: "~/.oh-my-zsh/custom/plugins/zsh-autosuggestions"

- name: Install history-substring-search plugin.
  git:
    repo: "https://github.com/zsh-users/zsh-history-substring-search"
    dest: "~/.oh-my-zsh/custom/plugins/zsh-history-substring-search"

- name: Install powerlevel10k.
  git:
    repo: "https://github.com/romkatv/powerlevel10k.git"
    depth: 1
    dest: "~/.oh-my-zsh/custom/themes/powerlevel10k"

- name: Create symlink for .aliases.
  file:     
    src: "~/.aliases"
    dest: "~/.oh-my-zsh/custom/zsh_aliases.zsh"
    state: link

